baseURL = "https://dbcourse2019.com"
languageCode = "en-us"
title = "Databases 2019"
theme = "blnk"
[outputFormats]
  [outputFormats.slide]
    mediaType = "text/html"
    name = "slide"
    path = "slides"
    isHTML = "true"
[outputs]
  home = ["HTML", "slide"]
  page = ["HTML", "slide"]
  post = ["HTML", "slide"]